name: FIREBASE_TEST_LAB

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  android-workflow:
    runs-on: ubuntu-latest
    name: Run on Firebase Test Lab
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk

      - id: auth
        name: Authenticate Google Cloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIAL }}
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      
      - name: Upload to Firebase Test Lab
        run: |
          pushd android
          ./gradlew app:assembleAndroidTest
          ./gradlew app:assembleDebug -Ptarget=`pwd`../../integration_test/main_test.dart
          popd

          echo '${{ secrets.GCP_FTL_KEY }}' | base64 --decode > ./gcloud_key_file.json
          # gcloud auth activate-service-account --key-file=./gcloud_key_file.json
          gcloud auth login --cred-file=./gcloud_key_file.json
          gcloud --quiet config set project '${{ secrets.GCP_PROJECT_ID }}'
          gcloud firebase test android run \
            --type instrumentation \
            --app build/app/outputs/apk/debug/app-debug.apk \
            --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
            --timeout 2m